[vendor]
# Please specify at least one of: vendor.ollama, vendor.openai

[vendor.ollama]
host = "http://gpu:11434"

[vendor.openai]
api_key = "sk-proj-XXX"

[query]
# type can be "singleton-text", "singleton-image", "batch-text", or "batch-image"
type = "batch-image" 

# target can be "ollama" or "openai"
# please also specify the corresponding vendor above!
target = "ollama"

# the model name and temperature (if supported) go here:
# model_name = "gpt-4o"
model_name = "gemma3:4b"
temperature = 0.2

[query.details]
# query type can be "singleton-text", "singleton-image", "batch-text", or "batch-image", see above
# different query types need different query details

# query type "singleton-text" needs instructions, context, and question
#instructions = "You are a helpful assistant. Please answer the question using the context below."
#context = "Dragan Ismailovic and Yasmina Kovzova are married. Their children are called Sohar (girl) and Boban (boy)"
#question = "What is the name of Dragan Ismailovic' and Yasmina Kovzova's daughter?"

# query type "singleton-image" needs instructions, question, and an image file
#instructions = "You are a visual assistant. Please answer specifically and as briefly as possible to the question."
#question = "Do you see raspberries? Please only answer 'yes', 'no', or 'uncertain'."
#image = "demo/berries.png"

# query type "batch-text" needs csv_file, csv_file_separator, colname_query_id, colname_instructions, colname_contexts, and colname_questions
#   csv_file contains the queries to be passed to the LLM
#csv_file = "temp/queries.csv"
#csv_file_separator = ","
#colname_query_id = "qid"
#colname_instructions = "instructions"
#colname_questions = "questions"
#colname_contexts = "contexts"

# query type "batch-image" needs instructions, question, and an image directory
instructions = "You are a visual assistant. Please answer specifically and as briefly as possible to the question."
question = "Do you see ships in the image? Please only answer 'yes', 'no', or 'uncertain'."
img_dir = "demo/input"
img_dir_glob = "image_*.jpg"
#img_qid = "filename-regex"    # 'filename' (default) or 'filename-regex'
#img_qid_regex = "\\d{2}"      # use matching sequence as query id 

[out]
# mode directs the output to standard output ("standard") or a csv file ("file")
mode = "file"                       # "file" or "standard"
csv_file = "demo/output/out1.csv"   # if file exists, out2.csv will be created
csv_file_separator = ";"            # the default is "," (comma); you can choose between comma, semicolon, and tab ("\t")